// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LondonTransportFareSystem.Models;

public partial class CustomerTransaction
{
    public int ID { get; set; }

    public Guid CustomerID { get; set; }

    public DateTime DateTime { get; set; }

    public int? ModeID { get; set; }

    public int? ZoneID { get; set; }

    public string Decription { get; set; }

    public decimal Debit { get; set; }

    public decimal CurrentBalance { get; set; }
}