// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LondonTransportFareSystem.Models;

public partial class Customer
{
    public Guid ID { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int Status { get; set; }

    public decimal Balance { get; set; }
}