// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using LondonTransportFareSystem.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace LondonTransportFareSystem.Models
{
    public partial interface ILondonTransportContextProcedures
    {
        Task<List<GetCurrentBalanceResult>> GetCurrentBalanceAsync(Guid? customerID, OutputParameter<decimal?> balance, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TopUpAccountResult>> TopUpAccountAsync(Guid? customerID, decimal? amount, OutputParameter<bool?> success, OutputParameter<decimal?> balance, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateTransactionOnSwipeInResult>> UpdateTransactionOnSwipeInAsync(Guid? customerID, int? modeID, int? stationID, OutputParameter<bool?> isAllowed, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UpdateTransactionOnSwipeOutResult>> UpdateTransactionOnSwipeOutAsync(Guid? customerID, int? modeID, int? stationID, OutputParameter<bool?> success, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
