// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LondonTransportFareSystem.Models;

public partial class ModeTube
{
    public int ID { get; set; }

    public int ModeID { get; set; }

    public string Name { get; set; }
}