// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LondonTransportFareSystem.Models;

public partial class ModeMaxFare
{
    public int ID { get; set; }

    public string Mode { get; set; }

    public decimal MaxFare { get; set; }
}