// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LondonTransportFareSystem.Models
{
    public partial class TopUpAccountResult
    {
        public bool? IsSuccess { get; set; }
        public decimal? Balance { get; set; }
    }
}
