// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LondonTransportFareSystem.Models;

public partial class TubeZone
{
    public int ID { get; set; }

    public int StationID { get; set; }

    public int ZoneID { get; set; }
}