// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LondonTransportFareSystem.Models;

public partial class Zone
{
    public int ID { get; set; }

    public string Name { get; set; }

    public decimal MinFare { get; set; }

    public decimal _2 { get; set; }

    public decimal _3 { get; set; }
}